# Generated by Django 2.2.2 on 2019-09-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('student', 'Alumno'), ('teacher', 'Maestro')], default='student', max_length=7),
        ),
    ]
