# Generated by Django 2.2.2 on 2019-09-22 15:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Curso')),
                ('description', models.TextField(verbose_name='Descripcion del curso')),
                ('date_start', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Creacion')),
                ('date_end', models.DateTimeField(verbose_name='Fecha de fin de curso')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo del examen')),
                ('date_application', models.DateTimeField(verbose_name='Fecha aplicaion del examen')),
            ],
        ),
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la unidad')),
                ('description', models.TextField(verbose_name='Descripcion de la unidad')),
                ('date_start', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de inicio')),
                ('date_end', models.DateTimeField(verbose_name='Fecha de fin de unidad')),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pregunta')),
                ('date_start', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de inicio')),
                ('type', models.TextField(verbose_name='tipo')),
                ('id_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Exam')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='id_unity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Unity'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='respuesta')),
                ('is_correct', models.BooleanField(verbose_name='Es correcta')),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Question')),
            ],
        ),
    ]
